// NOTE: this file is auto-generated, do not modify
/**
 * FFmpeg source filters (no input streams required).
 */


import { StreamType, type FFMpegFilterDef } from "@typed-ffmpeg/core/common/schema";
import { Default, Auto } from "@typed-ffmpeg/core/utils/types";
import { filterNodeFactory } from "@typed-ffmpeg/core/dag/factory";
import { merge } from "@typed-ffmpeg/core/utils/frozenRecord";
import { FilterableStream } from "@typed-ffmpeg/core/dag/baseStreams";
import { FilterNode, VideoStream, AudioStream } from "@typed-ffmpeg/core/dag/nodes";
import type {
  FFBoolean, FFInt, FFInt64, FFFloat, FFDouble, FFString,
  FFDuration, FFColor, FFFlags, FFDictionary, FFPixFmt,
  FFVideoRate, FFImageSize, FFRational, FFSampleFmt, FFBinary,
} from "@typed-ffmpeg/core/types";













/**
 * Buffer audio frames, and make them accessible to the filterchain.

 *
 * @param options.time_base - (from 0 to INT_MAX) (default 0/1)
 * @param options.sample_rate - (from 0 to INT_MAX) (default 0)
 * @param options.sample_fmt - (default none)
 * @param options.channel_layout -
 * @param options.channels - (from 0 to INT_MAX) (default 0)
 * @see https://ffmpeg.org/ffmpeg-filters.html#abuffer
 */
export function abuffer(



  options?: {
    time_base?: FFRational;
    sample_rate?: FFInt;
    sample_fmt?: FFSampleFmt;
    channel_layout?: FFString;
    channels?: FFInt;
extraOptions?: Record<string, unknown>;
  },
): AudioStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "abuffer", typingsInput: [], typingsOutput: ["audio"] },
    inputStreams,
    merge(
    {
      "time_base": options?.time_base,
      "sample_rate": options?.sample_rate,
      "sample_fmt": options?.sample_fmt,
      "channel_layout": options?.channel_layout,
      "channels": options?.channels,
},
    options?.extraOptions,
  ),
  );
return filterNode.audio(0) as unknown as AudioStream;
}














/**
 * Cross fade two input audio streams.

 *
 * @param options.inputs - set number of input files to cross fade (from 1 to INT_MAX) (default 2)
 * @param options.nb_samples - set number of samples for cross fade duration (from 1 to 2.14748e+08) (default 44100)
 * @param options.duration - set cross fade duration (default 0)
 * @param options.overlap - overlap 1st stream end with 2nd stream start (default true)
 * @param options.curve1 - set fade curve type for 1st stream (from -1 to 22) (default tri)
 * @param options.curve2 - set fade curve type for 2nd stream (from -1 to 22) (default tri)
 * @see https://ffmpeg.org/ffmpeg-filters.html#acrossfade
 */
export function acrossfade(

  streams: FilterableStream[],

  options?: {
    inputs?: FFInt;
    nb_samples?: FFInt64;
    duration?: FFDuration;
    overlap?: FFBoolean;
    curve1?: FFInt | "nofade" | "tri" | "qsin" | "esin" | "hsin" | "log" | "ipar" | "qua" | "cub" | "squ" | "cbr" | "par" | "exp" | "iqsin" | "ihsin" | "dese" | "desi" | "losi" | "sinc" | "isinc" | "quat" | "quatr" | "qsin2" | "hsin2";
    curve2?: FFInt | "nofade" | "tri" | "qsin" | "esin" | "hsin" | "log" | "ipar" | "qua" | "cub" | "squ" | "cbr" | "par" | "exp" | "iqsin" | "ihsin" | "dese" | "desi" | "losi" | "sinc" | "isinc" | "quat" | "quatr" | "qsin2" | "hsin2";
extraOptions?: Record<string, unknown>;
  },
): AudioStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "acrossfade", typingsInput: [], typingsOutput: ["audio"] },
    inputStreams,
    merge(
    {
      "inputs": options?.inputs,
      "nb_samples": options?.nb_samples,
      "duration": options?.duration,
      "overlap": options?.overlap,
      "curve1": options?.curve1,
      "curve2": options?.curve2,
},
    options?.extraOptions,
  ),
  );
return filterNode.audio(0) as unknown as AudioStream;
}








































/**
 * Generate an audio signal generated by an expression.

 *
 * @param options.exprs - set the '|'-separated list of channels expressions
 * @param options.nb_samples - set the number of samples per requested frame (from 0 to INT_MAX) (default 1024)
 * @param options.sample_rate - set the sample rate (default "44100")
 * @param options.duration - set audio duration (default -0.000001)
 * @param options.channel_layout - set channel layout
 * @see https://ffmpeg.org/ffmpeg-filters.html#aevalsrc
 */
export function aevalsrc(



  options?: {
    exprs?: FFString;
    nb_samples?: FFInt;
    sample_rate?: FFString;
    duration?: FFDuration;
    channel_layout?: FFString;
extraOptions?: Record<string, unknown>;
  },
): AudioStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "aevalsrc", typingsInput: [], typingsOutput: ["audio"] },
    inputStreams,
    merge(
    {
      "exprs": options?.exprs,
      "nb_samples": options?.nb_samples,
      "sample_rate": options?.sample_rate,
      "duration": options?.duration,
      "channel_layout": options?.channel_layout,
},
    options?.extraOptions,
  ),
  );
return filterNode.audio(0) as unknown as AudioStream;
}










/**
 * Generate a Fractional delay FIR coefficients.

 *
 * @param options.delay - set fractional delay (from 0 to 32767) (default 0)
 * @param options.sample_rate - set sample rate (from 1 to INT_MAX) (default 44100)
 * @param options.nb_samples - set the number of samples per requested frame (from 1 to INT_MAX) (default 1024)
 * @param options.taps - set number of taps for delay filter (from 0 to 32768) (default 0)
 * @param options.channel_layout - set channel layout (default "stereo")
 * @see https://ffmpeg.org/ffmpeg-filters.html#afdelaysrc
 */
export function afdelaysrc(



  options?: {
    delay?: FFDouble;
    sample_rate?: FFInt;
    nb_samples?: FFInt;
    taps?: FFInt;
    channel_layout?: FFString;
extraOptions?: Record<string, unknown>;
  },
): AudioStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "afdelaysrc", typingsInput: [], typingsOutput: ["audio"] },
    inputStreams,
    merge(
    {
      "delay": options?.delay,
      "sample_rate": options?.sample_rate,
      "nb_samples": options?.nb_samples,
      "taps": options?.taps,
      "channel_layout": options?.channel_layout,
},
    options?.extraOptions,
  ),
  );
return filterNode.audio(0) as unknown as AudioStream;
}










/**
 * Generate a FIR equalizer coefficients audio stream.

 *
 * @param options.preset - set equalizer preset (from -1 to 17) (default flat)
 * @param options.gains - set gain values per band (default "0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0")
 * @param options.bands - set central frequency values per band (default "25 40 63 100 160 250 400 630 1000 1600 2500 4000 6300 10000 16000 24000")
 * @param options.taps - set number of taps (from 16 to 65535) (default 4096)
 * @param options.sample_rate - set sample rate (from 1 to INT_MAX) (default 44100)
 * @param options.nb_samples - set the number of samples per requested frame (from 1 to INT_MAX) (default 1024)
 * @param options.interp - set the interpolation (from 0 to 1) (default linear)
 * @param options.phase - set the phase (from 0 to 1) (default min)
 * @see https://ffmpeg.org/ffmpeg-filters.html#afireqsrc
 */
export function afireqsrc(



  options?: {
    preset?: FFInt | "custom" | "flat" | "acoustic" | "bass" | "beats" | "classic" | "clear" | "deep bass" | "dubstep" | "electronic" | "hardstyle" | "hip-hop" | "jazz" | "metal" | "movie" | "pop" | "r\u0026b" | "rock" | "vocal booster";
    gains?: FFString;
    bands?: FFString;
    taps?: FFInt;
    sample_rate?: FFInt;
    nb_samples?: FFInt;
    interp?: FFInt | "linear" | "cubic";
    phase?: FFInt | "linear" | "min";
extraOptions?: Record<string, unknown>;
  },
): AudioStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "afireqsrc", typingsInput: [], typingsOutput: ["audio"] },
    inputStreams,
    merge(
    {
      "preset": options?.preset,
      "gains": options?.gains,
      "bands": options?.bands,
      "taps": options?.taps,
      "sample_rate": options?.sample_rate,
      "nb_samples": options?.nb_samples,
      "interp": options?.interp,
      "phase": options?.phase,
},
    options?.extraOptions,
  ),
  );
return filterNode.audio(0) as unknown as AudioStream;
}






/**
 * Generate a FIR coefficients audio stream.

 *
 * @param options.taps - set number of taps (from 9 to 65535) (default 1025)
 * @param options.frequency - set frequency points (default "0 1")
 * @param options.magnitude - set magnitude values (default "1 1")
 * @param options.phase - set phase values (default "0 0")
 * @param options.sample_rate - set sample rate (from 1 to INT_MAX) (default 44100)
 * @param options.nb_samples - set the number of samples per requested frame (from 1 to INT_MAX) (default 1024)
 * @param options.win_func - set window function (from 0 to 20) (default blackman)
 * @see https://ffmpeg.org/ffmpeg-filters.html#afirsrc
 */
export function afirsrc(



  options?: {
    taps?: FFInt;
    frequency?: FFString;
    magnitude?: FFString;
    phase?: FFString;
    sample_rate?: FFInt;
    nb_samples?: FFInt;
    win_func?: FFInt | "rect" | "bartlett" | "hann" | "hanning" | "hamming" | "blackman" | "welch" | "flattop" | "bharris" | "bnuttall" | "bhann" | "sine" | "nuttall" | "lanczos" | "gauss" | "tukey" | "dolph" | "cauchy" | "parzen" | "poisson" | "bohman" | "kaiser";
extraOptions?: Record<string, unknown>;
  },
): AudioStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "afirsrc", typingsInput: [], typingsOutput: ["audio"] },
    inputStreams,
    merge(
    {
      "taps": options?.taps,
      "frequency": options?.frequency,
      "magnitude": options?.magnitude,
      "phase": options?.phase,
      "sample_rate": options?.sample_rate,
      "nb_samples": options?.nb_samples,
      "win_func": options?.win_func,
},
    options?.extraOptions,
  ),
  );
return filterNode.audio(0) as unknown as AudioStream;
}






















/**
 * Temporally interleave audio inputs.

 *
 * @param options.nb_inputs - set number of inputs (from 1 to INT_MAX) (default 2)
 * @param options.duration - how to determine the end-of-stream (from 0 to 2) (default longest)
 * @see https://ffmpeg.org/ffmpeg-filters.html#interleave_002c-ainterleave
 */
export function ainterleave(

  streams: FilterableStream[],

  options?: {
    nb_inputs?: FFInt;
    duration?: FFInt | "longest" | "shortest" | "first";
extraOptions?: Record<string, unknown>;
  },
): AudioStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "ainterleave", typingsInput: [], typingsOutput: ["audio"] },
    inputStreams,
    merge(
    {
      "nb_inputs": options?.nb_inputs,
      "duration": options?.duration,
},
    options?.extraOptions,
  ),
  );
return filterNode.audio(0) as unknown as AudioStream;
}












/**
 * Generate all RGB colors.

 *
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @see https://ffmpeg.org/ffmpeg-filters.html#allrgb_002c-allyuv_002c-color_002c-colorchart_002c-colorspectrum_002c-haldclutsrc_002c-nullsrc_002c-pal75bars_002c-pal100bars_002c-rgbtestsrc_002c-smptebars_002c-smptehdbars_002c-testsrc_002c-testsrc2_002c-yuvtestsrc
 */
export function allrgb(



  options?: {
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "allrgb", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}






/**
 * Generate all yuv colors.

 *
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @see https://ffmpeg.org/ffmpeg-filters.html#allrgb_002c-allyuv_002c-color_002c-colorchart_002c-colorspectrum_002c-haldclutsrc_002c-nullsrc_002c-pal75bars_002c-pal100bars_002c-rgbtestsrc_002c-smptebars_002c-smptehdbars_002c-testsrc_002c-testsrc2_002c-yuvtestsrc
 */
export function allyuv(



  options?: {
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "allyuv", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}












/**
 * Merge two or more audio streams into a single multi-channel stream.

 *
 * @param options.inputs - specify the number of inputs (from 1 to 64) (default 2)
 * @param options.layout_mode - method used to determine the output channel layout (from 0 to 2) (default legacy)
 * @see https://ffmpeg.org/ffmpeg-filters.html#amerge
 */
export function amerge(

  streams: FilterableStream[],

  options?: {
    inputs?: FFInt;
    layout_mode?: FFInt | "legacy" | "reset" | "normal";
extraOptions?: Record<string, unknown>;
  },
): AudioStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "amerge", typingsInput: [], typingsOutput: ["audio"] },
    inputStreams,
    merge(
    {
      "inputs": options?.inputs,
      "layout_mode": options?.layout_mode,
},
    options?.extraOptions,
  ),
  );
return filterNode.audio(0) as unknown as AudioStream;
}








/**
 * Audio mixing.

 *
 * @param options.inputs - Number of inputs. (from 1 to 32767) (default 2)
 * @param options.duration - How to determine the end-of-stream. (from 0 to 2) (default longest)
 * @param options.dropout_transition - Transition time, in seconds, for volume renormalization when an input stream ends. (from 0 to INT_MAX) (default 2)
 * @param options.weights - Set weight for each input. (default "1 1")
 * @param options.normalize - Scale inputs (default true)
 * @see https://ffmpeg.org/ffmpeg-filters.html#amix
 */
export function amix(

  streams: FilterableStream[],

  options?: {
    inputs?: FFInt;
    duration?: FFInt | "longest" | "shortest" | "first";
    dropout_transition?: FFFloat;
    weights?: FFString;
    normalize?: FFBoolean;
extraOptions?: Record<string, unknown>;
  },
): AudioStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "amix", typingsInput: [], typingsOutput: ["audio"] },
    inputStreams,
    merge(
    {
      "inputs": options?.inputs,
      "duration": options?.duration,
      "dropout_transition": options?.dropout_transition,
      "weights": options?.weights,
      "normalize": options?.normalize,
},
    options?.extraOptions,
  ),
  );
return filterNode.audio(0) as unknown as AudioStream;
}






/**
 * Read audio from a movie source.

 *
 * @param options.filename -
 * @param options.format_name - set format name
 * @param options.stream_index - set stream index (from -1 to INT_MAX) (default -1)
 * @param options.seek_point - set seekpoint (seconds) (from 0 to 9.22337e+12) (default 0)
 * @param options.streams - set streams
 * @param options.loop - set loop count (from 0 to INT_MAX) (default 1)
 * @param options.discontinuity - set discontinuity threshold (default 0)
 * @param options.dec_threads - set the number of threads for decoding (from 0 to INT_MAX) (default 0)
 * @param options.format_opts - set format options for the opened file
 * @see https://ffmpeg.org/ffmpeg-filters.html#amovie
 */
export function amovie(



  options?: {
    filename?: FFString;
    format_name?: FFString;
    stream_index?: FFInt;
    seek_point?: FFDouble;
    streams?: FFString;
    loop?: FFInt;
    discontinuity?: FFDuration;
    dec_threads?: FFInt;
    format_opts?: FFDictionary;
extraOptions?: Record<string, unknown>;
  },
): FilterNode {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "amovie", typingsInput: [], typingsOutput: [] },
    inputStreams,
    merge(
    {
      "filename": options?.filename,
      "format_name": options?.format_name,
      "stream_index": options?.stream_index,
      "seek_point": options?.seek_point,
      "streams": options?.streams,
      "loop": options?.loop,
      "discontinuity": options?.discontinuity,
      "dec_threads": options?.dec_threads,
      "format_opts": options?.format_opts,
},
    options?.extraOptions,
  ),
  );
return filterNode;
}


















/**
 * Generate a noise audio signal.

 *
 * @param options.sample_rate - set sample rate (from 15 to INT_MAX) (default 48000)
 * @param options.amplitude - set amplitude (from 0 to 1) (default 1)
 * @param options.duration - set duration (default 0)
 * @param options.color - set noise color (from 0 to 5) (default white)
 * @param options.seed - set random seed (from -1 to UINT32_MAX) (default -1)
 * @param options.nb_samples - set the number of samples per requested frame (from 1 to INT_MAX) (default 1024)
 * @param options.density - set density (from 0 to 1) (default 0.05)
 * @see https://ffmpeg.org/ffmpeg-filters.html#anoisesrc
 */
export function anoisesrc(



  options?: {
    sample_rate?: FFInt;
    amplitude?: FFDouble;
    duration?: FFDuration;
    color?: FFInt | "white" | "pink" | "brown" | "blue" | "violet" | "velvet";
    seed?: FFInt64;
    nb_samples?: FFInt;
    density?: FFDouble;
extraOptions?: Record<string, unknown>;
  },
): AudioStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "anoisesrc", typingsInput: [], typingsOutput: ["audio"] },
    inputStreams,
    merge(
    {
      "sample_rate": options?.sample_rate,
      "amplitude": options?.amplitude,
      "duration": options?.duration,
      "color": options?.color,
      "seed": options?.seed,
      "nb_samples": options?.nb_samples,
      "density": options?.density,
},
    options?.extraOptions,
  ),
  );
return filterNode.audio(0) as unknown as AudioStream;
}










/**
 * Null audio source, return empty audio frames.

 *
 * @param options.channel_layout - set channel_layout (default "stereo")
 * @param options.sample_rate - set sample rate (from 1 to INT_MAX) (default 44100)
 * @param options.nb_samples - set the number of samples per requested frame (from 1 to 65535) (default 1024)
 * @param options.duration - set the audio duration (default -0.000001)
 * @see https://ffmpeg.org/ffmpeg-filters.html#anullsrc
 */
export function anullsrc(



  options?: {
    channel_layout?: FFString;
    sample_rate?: FFInt;
    nb_samples?: FFInt;
    duration?: FFDuration;
extraOptions?: Record<string, unknown>;
  },
): AudioStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "anullsrc", typingsInput: [], typingsOutput: ["audio"] },
    inputStreams,
    merge(
    {
      "channel_layout": options?.channel_layout,
      "sample_rate": options?.sample_rate,
      "nb_samples": options?.nb_samples,
      "duration": options?.duration,
},
    options?.extraOptions,
  ),
  );
return filterNode.audio(0) as unknown as AudioStream;
}






























































/**
 * Select audio streams

 *
 * @param options.inputs - number of input streams (from 2 to INT_MAX) (default 2)
 * @param options.map - input indexes to remap to outputs
 * @see https://ffmpeg.org/ffmpeg-filters.html#streamselect_002c-astreamselect
 */
export function astreamselect(

  streams: FilterableStream[],

  options?: {
    inputs?: FFInt;
    map?: FFString;
extraOptions?: Record<string, unknown>;
  },
): FilterNode {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "astreamselect", typingsInput: [], typingsOutput: [] },
    inputStreams,
    merge(
    {
      "inputs": options?.inputs,
      "map": options?.map,
},
    options?.extraOptions,
  ),
  );
return filterNode;
}




























/**
 * Generate an Audio Video Sync Test.

 *
 * @param options.size - set frame size (default "hd720")
 * @param options.framerate - set frame rate (default "30")
 * @param options.samplerate - set sample rate (from 8000 to 384000) (default 44100)
 * @param options.amplitude - set beep amplitude (from 0 to 1) (default 0.7)
 * @param options.period - set beep period (from 1 to 99) (default 3)
 * @param options.delay - set flash delay (from -30 to 30) (default 0)
 * @param options.cycle - set delay cycle (default false)
 * @param options.duration - set duration (default 0)
 * @param options.fg - set foreground color (default "white")
 * @param options.bg - set background color (default "black")
 * @param options.ag - set additional color (default "gray")
 * @see https://ffmpeg.org/ffmpeg-filters.html#avsynctest
 */
export function avsynctest(



  options?: {
    size?: FFImageSize;
    framerate?: FFVideoRate;
    samplerate?: FFInt;
    amplitude?: FFFloat;
    period?: FFInt;
    delay?: FFInt;
    cycle?: FFBoolean;
    duration?: FFDuration;
    fg?: FFColor;
    bg?: FFColor;
    ag?: FFColor;
extraOptions?: Record<string, unknown>;
  },
): FilterNode {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "avsynctest", typingsInput: [], typingsOutput: ["audio", "video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "framerate": options?.framerate,
      "samplerate": options?.samplerate,
      "amplitude": options?.amplitude,
      "period": options?.period,
      "delay": options?.delay,
      "cycle": options?.cycle,
      "duration": options?.duration,
      "fg": options?.fg,
      "bg": options?.bg,
      "ag": options?.ag,
},
    options?.extraOptions,
  ),
  );
return filterNode;
}




































/**
 * Block-Matching 3D denoiser.

 *
 * @param options.sigma - set denoising strength (from 0 to 99999.9) (default 1)
 * @param options.block - set size of local patch (from 8 to 64) (default 16)
 * @param options.bstep - set sliding step for processing blocks (from 1 to 64) (default 4)
 * @param options.group - set maximal number of similar blocks (from 1 to 256) (default 1)
 * @param options.range - set block matching range (from 1 to INT_MAX) (default 9)
 * @param options.mstep - set step for block matching (from 1 to 64) (default 1)
 * @param options.thmse - set threshold of mean square error for block matching (from 0 to INT_MAX) (default 0)
 * @param options.hdthr - set hard threshold for 3D transfer domain (from 0 to INT_MAX) (default 2.7)
 * @param options.estim - set filtering estimation mode (from 0 to 1) (default basic)
 * @param options.ref - have reference stream (default false)
 * @param options.planes - set planes to filter (from 0 to 15) (default 7)
 * @see https://ffmpeg.org/ffmpeg-filters.html#bm3d
 */
export function bm3d(

  streams: FilterableStream[],

  options?: {
    sigma?: FFFloat;
    block?: FFInt;
    bstep?: FFInt;
    group?: FFInt;
    range?: FFInt;
    mstep?: FFInt;
    thmse?: FFFloat;
    hdthr?: FFFloat;
    estim?: FFInt | "basic" | "final";
    ref?: FFBoolean;
    planes?: FFInt;
    enable?: FFString;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "bm3d", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "sigma": options?.sigma,
      "block": options?.block,
      "bstep": options?.bstep,
      "group": options?.group,
      "range": options?.range,
      "mstep": options?.mstep,
      "thmse": options?.thmse,
      "hdthr": options?.hdthr,
      "estim": options?.estim,
      "ref": options?.ref,
      "planes": options?.planes,
      "enable": options?.enable,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}








/**
 * Buffer video frames, and make them accessible to the filterchain.

 *
 * @param options.width - (from 0 to INT_MAX) (default 0)
 * @param options.video_size -
 * @param options.height - (from 0 to INT_MAX) (default 0)
 * @param options.pix_fmt - (default none)
 * @param options.sar - sample aspect ratio (from 0 to DBL_MAX) (default 0/1)
 * @param options.time_base - (from 0 to DBL_MAX) (default 0/1)
 * @param options.colorspace - select colorspace (from 0 to 17) (default unknown)
 * @param options.range - select color range (from 0 to 2) (default unspecified)
 * @param options.alpha_mode - select alpha mode (from 0 to 2) (default unspecified)
 * @see https://ffmpeg.org/ffmpeg-filters.html#buffer
 */
export function buffer(



  options?: {
    width?: FFInt;
    video_size?: FFImageSize;
    height?: FFInt;
    pix_fmt?: FFPixFmt;
    sar?: FFRational;
    time_base?: FFRational;
    colorspace?: FFInt | "gbr" | "bt709" | "unknown" | "fcc" | "bt470bg" | "smpte170m" | "smpte240m" | "ycgco" | "ycgco-re" | "ycgco-ro" | "bt2020nc" | "bt2020c" | "smpte2085" | "chroma-derived-nc" | "chroma-derived-c" | "ictcp" | "ipt-c2";
    range?: FFInt | "unspecified" | "unknown" | "limited" | "tv" | "mpeg" | "full" | "pc" | "jpeg";
    alpha_mode?: FFInt | "unspecified" | "unknown" | "straight" | "premultiplied";
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "buffer", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "width": options?.width,
      "video_size": options?.video_size,
      "height": options?.height,
      "pix_fmt": options?.pix_fmt,
      "sar": options?.sar,
      "time_base": options?.time_base,
      "colorspace": options?.colorspace,
      "range": options?.range,
      "alpha_mode": options?.alpha_mode,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}














/**
 * Create pattern generated by an elementary cellular automaton.

 *
 * @param options.filename - read initial pattern from file
 * @param options.pattern - set initial pattern
 * @param options.rate - set video rate (default "25")
 * @param options.size - set video size
 * @param options.rule - set rule (from 0 to 255) (default 110)
 * @param options.random_fill_ratio - set fill ratio for filling initial grid randomly (from 0 to 1) (default 0.618034)
 * @param options.random_seed - set the seed for filling the initial grid randomly (from -1 to UINT32_MAX) (default -1)
 * @param options.scroll - scroll pattern downward (default true)
 * @param options.start_full - start filling the whole video (default false)
 * @param options.full - start filling the whole video (default true)
 * @param options.stitch - stitch boundaries (default true)
 * @see https://ffmpeg.org/ffmpeg-filters.html#cellauto
 */
export function cellauto(



  options?: {
    filename?: FFString;
    pattern?: FFString;
    rate?: FFVideoRate;
    size?: FFImageSize;
    rule?: FFInt;
    random_fill_ratio?: FFDouble;
    random_seed?: FFInt64;
    scroll?: FFBoolean;
    start_full?: FFBoolean;
    full?: FFBoolean;
    stitch?: FFBoolean;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "cellauto", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "filename": options?.filename,
      "pattern": options?.pattern,
      "rate": options?.rate,
      "size": options?.size,
      "rule": options?.rule,
      "random_fill_ratio": options?.random_fill_ratio,
      "random_seed": options?.random_seed,
      "scroll": options?.scroll,
      "start_full": options?.start_full,
      "full": options?.full,
      "stitch": options?.stitch,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}
























/**
 * Provide an uniformly colored input.

 *
 * @param options.color - set color (default "black")
 * @param options.size - set video size (default "320x240")
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @see https://ffmpeg.org/ffmpeg-filters.html#allrgb_002c-allyuv_002c-color_002c-colorchart_002c-colorspectrum_002c-haldclutsrc_002c-nullsrc_002c-pal75bars_002c-pal100bars_002c-rgbtestsrc_002c-smptebars_002c-smptehdbars_002c-testsrc_002c-testsrc2_002c-yuvtestsrc
 */
export function color(



  options?: {
    color?: FFColor;
    size?: FFImageSize;
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "color", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "color": options?.color,
      "size": options?.size,
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}










/**
 * Generate color checker chart.

 *
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @param options.patch_size - set the single patch size (default "64x64")
 * @param options.preset - set the color checker chart preset (from 0 to 1) (default reference)
 * @see https://ffmpeg.org/ffmpeg-filters.html#allrgb_002c-allyuv_002c-color_002c-colorchart_002c-colorspectrum_002c-haldclutsrc_002c-nullsrc_002c-pal75bars_002c-pal100bars_002c-rgbtestsrc_002c-smptebars_002c-smptehdbars_002c-testsrc_002c-testsrc2_002c-yuvtestsrc
 */
export function colorchart(



  options?: {
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
    patch_size?: FFImageSize;
    preset?: FFInt | "reference" | "skintones";
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "colorchart", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
      "patch_size": options?.patch_size,
      "preset": options?.preset,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}


























/**
 * Generate colors spectrum.

 *
 * @param options.size - set video size (default "320x240")
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @param options._type - set the color spectrum type (from 0 to 2) (default black)
 * @see https://ffmpeg.org/ffmpeg-filters.html#allrgb_002c-allyuv_002c-color_002c-colorchart_002c-colorspectrum_002c-haldclutsrc_002c-nullsrc_002c-pal75bars_002c-pal100bars_002c-rgbtestsrc_002c-smptebars_002c-smptehdbars_002c-testsrc_002c-testsrc2_002c-yuvtestsrc
 */
export function colorspectrum(



  options?: {
    size?: FFImageSize;
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
    _type?: FFInt | "black" | "white" | "all";
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "colorspectrum", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
      "type": options?._type,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}












/**
 * Concatenate audio and video streams.

 *
 * @param options.n - specify the number of segments (from 1 to INT_MAX) (default 2)
 * @param options.v - specify the number of video streams (from 0 to INT_MAX) (default 1)
 * @param options.a - specify the number of audio streams (from 0 to INT_MAX) (default 0)
 * @param options.unsafe - enable unsafe mode (default false)
 * @see https://ffmpeg.org/ffmpeg-filters.html#concat
 */
export function concat(

  streams: FilterableStream[],

  options?: {
    n?: FFInt;
    v?: FFInt;
    a?: FFInt;
    unsafe?: FFBoolean;
extraOptions?: Record<string, unknown>;
  },
): FilterNode {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "concat", typingsInput: [], typingsOutput: [] },
    inputStreams,
    merge(
    {
      "n": options?.n,
      "v": options?.v,
      "a": options?.a,
      "unsafe": options?.unsafe,
},
    options?.extraOptions,
  ),
  );
return filterNode;
}














/**
 * Video source using image generators of CoreImage API.
 *
 * Note: New in FFmpeg 8.0.
 *
 * @param options.size - set video size (default "320x240")
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @param options.list_filters - list available filters (default false)
 * @param options.list_generators - list available generators (default false)
 * @param options.filter - names and options of filters to apply
 * @param options.output_rect - output rectangle within output image
 * @see https://ffmpeg.org/ffmpeg-filters.html#coreimagesrc
 */
export function coreimagesrc(



  options?: {
    size?: FFImageSize;
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
    list_filters?: FFBoolean;
    list_generators?: FFBoolean;
    filter?: FFString;
    output_rect?: FFString;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "coreimagesrc", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
      "list_filters": options?.list_filters,
      "list_generators": options?.list_generators,
      "filter": options?.filter,
      "output_rect": options?.output_rect,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}


































/**
 * Decimate frames (post field matching filter).

 *
 * @param options.cycle - set the number of frame from which one will be dropped (from 2 to 25) (default 5)
 * @param options.dupthresh - set duplicate threshold (from 0 to 100) (default 1.1)
 * @param options.scthresh - set scene change threshold (from 0 to 100) (default 15)
 * @param options.blockx - set the size of the x-axis blocks used during metric calculations (from 4 to 512) (default 32)
 * @param options.blocky - set the size of the y-axis blocks used during metric calculations (from 4 to 512) (default 32)
 * @param options.ppsrc - mark main input as a pre-processed input and activate clean source input stream (default false)
 * @param options.chroma - set whether or not chroma is considered in the metric calculations (default true)
 * @param options.mixed - set whether or not the input only partially contains content to be decimated (default false)
 * @see https://ffmpeg.org/ffmpeg-filters.html#decimate
 */
export function decimate(

  streams: FilterableStream[],

  options?: {
    cycle?: FFInt;
    dupthresh?: FFDouble;
    scthresh?: FFDouble;
    blockx?: FFInt;
    blocky?: FFInt;
    ppsrc?: FFBoolean;
    chroma?: FFBoolean;
    mixed?: FFBoolean;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "decimate", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "cycle": options?.cycle,
      "dupthresh": options?.dupthresh,
      "scthresh": options?.scthresh,
      "blockx": options?.blockx,
      "blocky": options?.blocky,
      "ppsrc": options?.ppsrc,
      "chroma": options?.chroma,
      "mixed": options?.mixed,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}


















































































/**
 * Field matching for inverse telecine.

 *
 * @param options.order - specify the assumed field order (from -1 to 1) (default auto)
 * @param options.mode - set the matching mode or strategy to use (from 0 to 5) (default pc_n)
 * @param options.ppsrc - mark main input as a pre-processed input and activate clean source input stream (default false)
 * @param options.field - set the field to match from (from -1 to 1) (default auto)
 * @param options.mchroma - set whether or not chroma is included during the match comparisons (default true)
 * @param options.y0 - define an exclusion band which excludes the lines between y0 and y1 from the field matching decision (from 0 to INT_MAX) (default 0)
 * @param options.scthresh - set scene change detection threshold (from 0 to 100) (default 12)
 * @param options.combmatch - set combmatching mode (from 0 to 2) (default sc)
 * @param options.combdbg - enable comb debug (from 0 to 2) (default none)
 * @param options.cthresh - set the area combing threshold used for combed frame detection (from -1 to 255) (default 9)
 * @param options.chroma - set whether or not chroma is considered in the combed frame decision (default false)
 * @param options.blockx - set the x-axis size of the window used during combed frame detection (from 4 to 512) (default 16)
 * @param options.blocky - set the y-axis size of the window used during combed frame detection (from 4 to 512) (default 16)
 * @param options.combpel - set the number of combed pixels inside any of the blocky by blockx size blocks on the frame for the frame to be detected as combed (from 0 to INT_MAX) (default 80)
 * @see https://ffmpeg.org/ffmpeg-filters.html#fieldmatch
 */
export function fieldmatch(

  streams: FilterableStream[],

  options?: {
    order?: FFInt | "auto" | "bff" | "tff";
    mode?: FFInt | "pc" | "pc_n" | "pc_u" | "pc_n_ub" | "pcn" | "pcn_ub";
    ppsrc?: FFBoolean;
    field?: FFInt | "auto" | "bottom" | "top";
    mchroma?: FFBoolean;
    y0?: FFInt;
    scthresh?: FFDouble;
    combmatch?: FFInt | "none" | "sc" | "full";
    combdbg?: FFInt | "none" | "pcn" | "pcnub";
    cthresh?: FFInt;
    chroma?: FFBoolean;
    blockx?: FFInt;
    blocky?: FFInt;
    combpel?: FFInt;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "fieldmatch", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "order": options?.order,
      "mode": options?.mode,
      "ppsrc": options?.ppsrc,
      "field": options?.field,
      "mchroma": options?.mchroma,
      "y0": options?.y0,
      "scthresh": options?.scthresh,
      "combmatch": options?.combmatch,
      "combdbg": options?.combdbg,
      "cthresh": options?.cthresh,
      "chroma": options?.chroma,
      "blockx": options?.blockx,
      "blocky": options?.blocky,
      "combpel": options?.combpel,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}










































/**
 * Draw a gradients.

 *
 * @param options.size - set frame size (default "640x480")
 * @param options.rate - set frame rate (default "25")
 * @param options.c0 - set 1st color (default "random")
 * @param options.c1 - set 2nd color (default "random")
 * @param options.c2 - set 3rd color (default "random")
 * @param options.c3 - set 4th color (default "random")
 * @param options.c4 - set 5th color (default "random")
 * @param options.c5 - set 6th color (default "random")
 * @param options.c6 - set 7th color (default "random")
 * @param options.c7 - set 8th color (default "random")
 * @param options.x0 - set gradient line source x0 (from -1 to INT_MAX) (default -1)
 * @param options.y0 - set gradient line source y0 (from -1 to INT_MAX) (default -1)
 * @param options.x1 - set gradient line destination x1 (from -1 to INT_MAX) (default -1)
 * @param options.y1 - set gradient line destination y1 (from -1 to INT_MAX) (default -1)
 * @param options.nb_colors - set the number of colors (from 2 to 8) (default 2)
 * @param options.seed - set the seed (from -1 to UINT32_MAX) (default -1)
 * @param options.duration - set video duration (default -0.000001)
 * @param options.speed - set gradients rotation speed (from 0 to 1) (default 0.01)
 * @param options._type - set gradient type (from 0 to 4) (default linear)
 * @see https://ffmpeg.org/ffmpeg-filters.html#gradients
 */
export function gradients(



  options?: {
    size?: FFImageSize;
    rate?: FFVideoRate;
    c0?: FFColor;
    c1?: FFColor;
    c2?: FFColor;
    c3?: FFColor;
    c4?: FFColor;
    c5?: FFColor;
    c6?: FFColor;
    c7?: FFColor;
    x0?: FFInt;
    y0?: FFInt;
    x1?: FFInt;
    y1?: FFInt;
    nb_colors?: FFInt;
    seed?: FFInt64;
    duration?: FFDuration;
    speed?: FFFloat;
    _type?: FFInt | "linear" | "radial" | "circular" | "spiral" | "square";
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "gradients", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "rate": options?.rate,
      "c0": options?.c0,
      "c1": options?.c1,
      "c2": options?.c2,
      "c3": options?.c3,
      "c4": options?.c4,
      "c5": options?.c5,
      "c6": options?.c6,
      "c7": options?.c7,
      "x0": options?.x0,
      "y0": options?.y0,
      "x1": options?.x1,
      "y1": options?.y1,
      "nb_colors": options?.nb_colors,
      "seed": options?.seed,
      "duration": options?.duration,
      "speed": options?.speed,
      "type": options?._type,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}












/**
 * Apply Guided filter.

 *
 * @param options.radius - set the box radius (from 1 to 20) (default 3)
 * @param options.eps - set the regularization parameter (with square) (from 0 to 1) (default 0.01)
 * @param options.mode - set filtering mode (0: basic mode; 1: fast mode) (from 0 to 1) (default basic)
 * @param options.sub - subsampling ratio for fast mode (from 2 to 64) (default 4)
 * @param options.guidance - set guidance mode (0: off mode; 1: on mode) (from 0 to 1) (default off)
 * @param options.planes - set planes to filter (from 0 to 15) (default 1)
 * @see https://ffmpeg.org/ffmpeg-filters.html#guided
 */
export function guided(

  streams: FilterableStream[],

  options?: {
    radius?: FFInt;
    eps?: FFFloat;
    mode?: FFInt | "basic" | "fast";
    sub?: FFInt;
    guidance?: FFInt | "off" | "on";
    planes?: FFInt;
    enable?: FFString;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "guided", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "radius": options?.radius,
      "eps": options?.eps,
      "mode": options?.mode,
      "sub": options?.sub,
      "guidance": options?.guidance,
      "planes": options?.planes,
      "enable": options?.enable,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}










/**
 * Provide an identity Hald CLUT.

 *
 * @param options.level - set level (from 2 to 16) (default 6)
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @see https://ffmpeg.org/ffmpeg-filters.html#allrgb_002c-allyuv_002c-color_002c-colorchart_002c-colorspectrum_002c-haldclutsrc_002c-nullsrc_002c-pal75bars_002c-pal100bars_002c-rgbtestsrc_002c-smptebars_002c-smptehdbars_002c-testsrc_002c-testsrc2_002c-yuvtestsrc
 */
export function haldclutsrc(



  options?: {
    level?: FFInt;
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "haldclutsrc", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "level": options?.level,
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}








/**
 * Apply headphone binaural spatialization with HRTFs in additional streams.

 *
 * @param options.map - set channels convolution mappings
 * @param options.gain - set gain in dB (from -20 to 40) (default 0)
 * @param options.lfe - set lfe gain in dB (from -20 to 40) (default 0)
 * @param options._type - set processing (from 0 to 1) (default freq)
 * @param options.size - set frame size (from 1024 to 96000) (default 1024)
 * @param options.hrir - set hrir format (from 0 to 1) (default stereo)
 * @see https://ffmpeg.org/ffmpeg-filters.html#headphone
 */
export function headphone(

  streams: FilterableStream[],

  options?: {
    map?: FFString;
    gain?: FFFloat;
    lfe?: FFFloat;
    _type?: FFInt | "time" | "freq";
    size?: FFInt;
    hrir?: FFInt | "stereo" | "multich";
extraOptions?: Record<string, unknown>;
  },
): AudioStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "headphone", typingsInput: [], typingsOutput: ["audio"] },
    inputStreams,
    merge(
    {
      "map": options?.map,
      "gain": options?.gain,
      "lfe": options?.lfe,
      "type": options?._type,
      "size": options?.size,
      "hrir": options?.hrir,
},
    options?.extraOptions,
  ),
  );
return filterNode.audio(0) as unknown as AudioStream;
}












/**
 * Generate a Hilbert transform FIR coefficients.

 *
 * @param options.sample_rate - set sample rate (from 1 to INT_MAX) (default 44100)
 * @param options.taps - set number of taps (from 11 to 65535) (default 22051)
 * @param options.nb_samples - set the number of samples per requested frame (from 1 to INT_MAX) (default 1024)
 * @param options.win_func - set window function (from 0 to 20) (default blackman)
 * @see https://ffmpeg.org/ffmpeg-filters.html#hilbert
 */
export function hilbert(



  options?: {
    sample_rate?: FFInt;
    taps?: FFInt;
    nb_samples?: FFInt;
    win_func?: FFInt | "rect" | "bartlett" | "hann" | "hanning" | "hamming" | "blackman" | "welch" | "flattop" | "bharris" | "bnuttall" | "bhann" | "sine" | "nuttall" | "lanczos" | "gauss" | "tukey" | "dolph" | "cauchy" | "parzen" | "poisson" | "bohman" | "kaiser";
extraOptions?: Record<string, unknown>;
  },
): AudioStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "hilbert", typingsInput: [], typingsOutput: ["audio"] },
    inputStreams,
    merge(
    {
      "sample_rate": options?.sample_rate,
      "taps": options?.taps,
      "nb_samples": options?.nb_samples,
      "win_func": options?.win_func,
},
    options?.extraOptions,
  ),
  );
return filterNode.audio(0) as unknown as AudioStream;
}














/**
 * Stack video inputs horizontally.

 *
 * @param options.inputs - set number of inputs (from 2 to INT_MAX) (default 2)
 * @param options.shortest - force termination when the shortest input terminates (default false)
 * @see https://ffmpeg.org/ffmpeg-filters.html#hstack
 */
export function hstack(

  streams: FilterableStream[],

  options?: {
    inputs?: FFInt;
    shortest?: FFBoolean;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "hstack", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "inputs": options?.inputs,
      "shortest": options?.shortest,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}
































/**
 * Temporally interleave video inputs.

 *
 * @param options.nb_inputs - set number of inputs (from 1 to INT_MAX) (default 2)
 * @param options.duration - how to determine the end-of-stream (from 0 to 2) (default longest)
 * @see https://ffmpeg.org/ffmpeg-filters.html#interleave_002c-ainterleave
 */
export function interleave(

  streams: FilterableStream[],

  options?: {
    nb_inputs?: FFInt;
    duration?: FFInt | "longest" | "shortest" | "first";
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "interleave", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "nb_inputs": options?.nb_inputs,
      "duration": options?.duration,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}






/**
 * Join multiple audio streams into multi-channel output.

 *
 * @param options.inputs - Number of input streams. (from 1 to INT_MAX) (default 2)
 * @param options.channel_layout - Channel layout of the output stream. (default "stereo")
 * @param options.map - A comma-separated list of channels maps in the format 'input_stream.input_channel-output_channel.
 * @see https://ffmpeg.org/ffmpeg-filters.html#join
 */
export function join(

  streams: FilterableStream[],

  options?: {
    inputs?: FFInt;
    channel_layout?: FFString;
    map?: FFString;
extraOptions?: Record<string, unknown>;
  },
): AudioStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "join", typingsInput: [], typingsOutput: ["audio"] },
    inputStreams,
    merge(
    {
      "inputs": options?.inputs,
      "channel_layout": options?.channel_layout,
      "map": options?.map,
},
    options?.extraOptions,
  ),
  );
return filterNode.audio(0) as unknown as AudioStream;
}
















/**
 * Create life.

 *
 * @param options.filename - set source file
 * @param options.size - set video size
 * @param options.rate - set video rate (default "25")
 * @param options.rule - set rule (default "B3/S23")
 * @param options.random_fill_ratio - set fill ratio for filling initial grid randomly (from 0 to 1) (default 0.618034)
 * @param options.random_seed - set the seed for filling the initial grid randomly (from -1 to UINT32_MAX) (default -1)
 * @param options.stitch - stitch boundaries (default true)
 * @param options.mold - set mold speed for dead cells (from 0 to 255) (default 0)
 * @param options.life_color - set life color (default "white")
 * @param options.death_color - set death color (default "black")
 * @param options.mold_color - set mold color (default "black")
 * @see https://ffmpeg.org/ffmpeg-filters.html#life
 */
export function life(



  options?: {
    filename?: FFString;
    size?: FFImageSize;
    rate?: FFVideoRate;
    rule?: FFString;
    random_fill_ratio?: FFDouble;
    random_seed?: FFInt64;
    stitch?: FFBoolean;
    mold?: FFInt;
    life_color?: FFColor;
    death_color?: FFColor;
    mold_color?: FFColor;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "life", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "filename": options?.filename,
      "size": options?.size,
      "rate": options?.rate,
      "rule": options?.rule,
      "random_fill_ratio": options?.random_fill_ratio,
      "random_seed": options?.random_seed,
      "stitch": options?.stitch,
      "mold": options?.mold,
      "life_color": options?.life_color,
      "death_color": options?.death_color,
      "mold_color": options?.mold_color,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}






/**
 * Apply filtering with limiting difference.

 *
 * @param options.threshold - set the threshold (from 0 to 1) (default 0.00392157)
 * @param options.elasticity - set the elasticity (from 0 to 10) (default 2)
 * @param options.reference - enable reference stream (default false)
 * @param options.planes - set the planes to filter (from 0 to 15) (default 15)
 * @see https://ffmpeg.org/ffmpeg-filters.html#limitdiff
 */
export function limitdiff(

  streams: FilterableStream[],

  options?: {
    threshold?: FFFloat;
    elasticity?: FFFloat;
    reference?: FFBoolean;
    planes?: FFInt;
    enable?: FFString;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "limitdiff", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "threshold": options?.threshold,
      "elasticity": options?.elasticity,
      "reference": options?.reference,
      "planes": options?.planes,
      "enable": options?.enable,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}






























/**
 * Render a Mandelbrot fractal.

 *
 * @param options.size - set frame size (default "640x480")
 * @param options.rate - set frame rate (default "25")
 * @param options.maxiter - set max iterations number (from 1 to INT_MAX) (default 7189)
 * @param options.start_x - set the initial x position (from -100 to 100) (default -0.743644)
 * @param options.start_y - set the initial y position (from -100 to 100) (default -0.131826)
 * @param options.start_scale - set the initial scale value (from 0 to FLT_MAX) (default 3)
 * @param options.end_scale - set the terminal scale value (from 0 to FLT_MAX) (default 0.3)
 * @param options.end_pts - set the terminal pts value (from 0 to I64_MAX) (default 400)
 * @param options.bailout - set the bailout value (from 0 to FLT_MAX) (default 10)
 * @param options.morphxf - set morph x frequency (from -FLT_MAX to FLT_MAX) (default 0.01)
 * @param options.morphyf - set morph y frequency (from -FLT_MAX to FLT_MAX) (default 0.0123)
 * @param options.morphamp - set morph amplitude (from -FLT_MAX to FLT_MAX) (default 0)
 * @param options.outer - set outer coloring mode (from 0 to INT_MAX) (default normalized_iteration_count)
 * @param options.inner - set inner coloring mode (from 0 to INT_MAX) (default mincol)
 * @see https://ffmpeg.org/ffmpeg-filters.html#mandelbrot
 */
export function mandelbrot(



  options?: {
    size?: FFImageSize;
    rate?: FFVideoRate;
    maxiter?: FFInt;
    start_x?: FFDouble;
    start_y?: FFDouble;
    start_scale?: FFDouble;
    end_scale?: FFDouble;
    end_pts?: FFDouble;
    bailout?: FFDouble;
    morphxf?: FFDouble;
    morphyf?: FFDouble;
    morphamp?: FFDouble;
    outer?: FFInt | "iteration_count" | "normalized_iteration_count" | "white" | "outz";
    inner?: FFInt | "black" | "period" | "convergence" | "mincol";
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "mandelbrot", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "rate": options?.rate,
      "maxiter": options?.maxiter,
      "start_x": options?.start_x,
      "start_y": options?.start_y,
      "start_scale": options?.start_scale,
      "end_scale": options?.end_scale,
      "end_pts": options?.end_pts,
      "bailout": options?.bailout,
      "morphxf": options?.morphxf,
      "morphyf": options?.morphyf,
      "morphamp": options?.morphamp,
      "outer": options?.outer,
      "inner": options?.inner,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}
























/**
 * Merge planes.

 *
 * @param options.mapping - set input to output plane mapping (from -1 to 8.58993e+08) (default -1)
 * @param options.format - set output pixel format (default yuva444p)
 * @param options.map0s - set 1st input to output stream mapping (from 0 to 3) (default 0)
 * @param options.map0p - set 1st input to output plane mapping (from 0 to 3) (default 0)
 * @param options.map1s - set 2nd input to output stream mapping (from 0 to 3) (default 0)
 * @param options.map1p - set 2nd input to output plane mapping (from 0 to 3) (default 0)
 * @param options.map2s - set 3rd input to output stream mapping (from 0 to 3) (default 0)
 * @param options.map2p - set 3rd input to output plane mapping (from 0 to 3) (default 0)
 * @param options.map3s - set 4th input to output stream mapping (from 0 to 3) (default 0)
 * @param options.map3p - set 4th input to output plane mapping (from 0 to 3) (default 0)
 * @see https://ffmpeg.org/ffmpeg-filters.html#mergeplanes
 */
export function mergeplanes(

  streams: FilterableStream[],

  options?: {
    mapping?: FFInt;
    format?: FFPixFmt;
    map0s?: FFInt;
    map0p?: FFInt;
    map1s?: FFInt;
    map1p?: FFInt;
    map2s?: FFInt;
    map2p?: FFInt;
    map3s?: FFInt;
    map3p?: FFInt;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "mergeplanes", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "mapping": options?.mapping,
      "format": options?.format,
      "map0s": options?.map0s,
      "map0p": options?.map0p,
      "map1s": options?.map1s,
      "map1p": options?.map1p,
      "map2s": options?.map2s,
      "map2p": options?.map2p,
      "map3s": options?.map3s,
      "map3p": options?.map3p,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}














/**
 * Mix video inputs.

 *
 * @param options.inputs - set number of inputs (from 2 to 32767) (default 2)
 * @param options.weights - set weight for each input (default "1 1")
 * @param options.scale - set scale (from 0 to 32767) (default 0)
 * @param options.planes - set what planes to filter (default F)
 * @param options.duration - how to determine end of stream (from 0 to 2) (default longest)
 * @see https://ffmpeg.org/ffmpeg-filters.html#mix
 */
export function mix(

  streams: FilterableStream[],

  options?: {
    inputs?: FFInt;
    weights?: FFString;
    scale?: FFFloat;
    planes?: FFFlags;
    duration?: FFInt | "longest" | "shortest" | "first";
    enable?: FFString;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "mix", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "inputs": options?.inputs,
      "weights": options?.weights,
      "scale": options?.scale,
      "planes": options?.planes,
      "duration": options?.duration,
      "enable": options?.enable,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}










/**
 * Read from a movie source.

 *
 * @param options.filename -
 * @param options.format_name - set format name
 * @param options.stream_index - set stream index (from -1 to INT_MAX) (default -1)
 * @param options.seek_point - set seekpoint (seconds) (from 0 to 9.22337e+12) (default 0)
 * @param options.streams - set streams
 * @param options.loop - set loop count (from 0 to INT_MAX) (default 1)
 * @param options.discontinuity - set discontinuity threshold (default 0)
 * @param options.dec_threads - set the number of threads for decoding (from 0 to INT_MAX) (default 0)
 * @param options.format_opts - set format options for the opened file
 * @see https://ffmpeg.org/ffmpeg-filters.html#movie
 */
export function movie(



  options?: {
    filename?: FFString;
    format_name?: FFString;
    stream_index?: FFInt;
    seek_point?: FFDouble;
    streams?: FFString;
    loop?: FFInt;
    discontinuity?: FFDuration;
    dec_threads?: FFInt;
    format_opts?: FFDictionary;
extraOptions?: Record<string, unknown>;
  },
): FilterNode {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "movie", typingsInput: [], typingsOutput: [] },
    inputStreams,
    merge(
    {
      "filename": options?.filename,
      "format_name": options?.format_name,
      "stream_index": options?.stream_index,
      "seek_point": options?.seek_point,
      "streams": options?.streams,
      "loop": options?.loop,
      "discontinuity": options?.discontinuity,
      "dec_threads": options?.dec_threads,
      "format_opts": options?.format_opts,
},
    options?.extraOptions,
  ),
  );
return filterNode;
}








/**
 * Generate various test pattern.

 *
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.test - set test to perform (from 0 to INT_MAX) (default all)
 * @param options.max_frames - Set the maximum number of frames generated for each test (from 1 to I64_MAX) (default 30)
 * @see https://ffmpeg.org/ffmpeg-filters.html#mptestsrc
 */
export function mptestsrc(



  options?: {
    rate?: FFVideoRate;
    duration?: FFDuration;
    test?: FFInt | "dc_luma" | "dc_chroma" | "freq_luma" | "freq_chroma" | "amp_luma" | "amp_chroma" | "cbp" | "mv" | "ring1" | "ring2" | "all";
    max_frames?: FFInt64;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "mptestsrc", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "rate": options?.rate,
      "duration": options?.duration,
      "test": options?.test,
      "max_frames": options?.max_frames,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}


























/**
 * Null video source, return unprocessed video frames.

 *
 * @param options.size - set video size (default "320x240")
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @see https://ffmpeg.org/ffmpeg-filters.html#allrgb_002c-allyuv_002c-color_002c-colorchart_002c-colorspectrum_002c-haldclutsrc_002c-nullsrc_002c-pal75bars_002c-pal100bars_002c-rgbtestsrc_002c-smptebars_002c-smptehdbars_002c-testsrc_002c-testsrc2_002c-yuvtestsrc
 */
export function nullsrc(



  options?: {
    size?: FFImageSize;
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "nullsrc", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}














/**
 * Generate PAL 100% color bars.

 *
 * @param options.size - set video size (default "320x240")
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @see https://ffmpeg.org/ffmpeg-filters.html#allrgb_002c-allyuv_002c-color_002c-colorchart_002c-colorspectrum_002c-haldclutsrc_002c-nullsrc_002c-pal75bars_002c-pal100bars_002c-rgbtestsrc_002c-smptebars_002c-smptehdbars_002c-testsrc_002c-testsrc2_002c-yuvtestsrc
 */
export function pal100bars(



  options?: {
    size?: FFImageSize;
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "pal100bars", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}






/**
 * Generate PAL 75% color bars.

 *
 * @param options.size - set video size (default "320x240")
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @see https://ffmpeg.org/ffmpeg-filters.html#allrgb_002c-allyuv_002c-color_002c-colorchart_002c-colorspectrum_002c-haldclutsrc_002c-nullsrc_002c-pal75bars_002c-pal100bars_002c-rgbtestsrc_002c-smptebars_002c-smptehdbars_002c-testsrc_002c-testsrc2_002c-yuvtestsrc
 */
export function pal75bars(



  options?: {
    size?: FFImageSize;
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "pal75bars", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}












/**
 * Generate Perlin noise

 *
 * @param options.size - set video size (default "320x240")
 * @param options.rate - set video rate (default "25")
 * @param options.octaves - set the number of components to use to generate the noise (from 1 to INT_MAX) (default 1)
 * @param options.persistence - set the octaves persistence (from 0 to DBL_MAX) (default 1)
 * @param options.xscale - set x-scale factor (from 0 to DBL_MAX) (default 1)
 * @param options.yscale - set y-scale factor (from 0 to DBL_MAX) (default 1)
 * @param options.tscale - set t-scale factor (from 0 to DBL_MAX) (default 1)
 * @param options.random_mode - set random mode used to compute initial pattern (from 0 to 2) (default random)
 * @param options.random_seed - set the seed for filling the initial pattern (from 0 to UINT32_MAX) (default 0)
 * @see https://ffmpeg.org/ffmpeg-filters.html#perlin
 */
export function perlin(



  options?: {
    size?: FFImageSize;
    rate?: FFVideoRate;
    octaves?: FFInt;
    persistence?: FFDouble;
    xscale?: FFDouble;
    yscale?: FFDouble;
    tscale?: FFDouble;
    random_mode?: FFInt | "random" | "ken" | "seed";
    random_seed?: FFInt;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "perlin", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "rate": options?.rate,
      "octaves": options?.octaves,
      "persistence": options?.persistence,
      "xscale": options?.xscale,
      "yscale": options?.yscale,
      "tscale": options?.tscale,
      "random_mode": options?.random_mode,
      "random_seed": options?.random_seed,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}






















/**
 * PreMultiply first stream with first plane of second stream.

 *
 * @param options.planes - set planes (from 0 to 15) (default 15)
 * @param options.inplace - enable inplace mode (default false)
 * @see https://ffmpeg.org/ffmpeg-filters.html#premultiply
 */
export function premultiply(

  streams: FilterableStream[],

  options?: {
    planes?: FFInt;
    inplace?: FFBoolean;
    enable?: FFString;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "premultiply", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "planes": options?.planes,
      "inplace": options?.inplace,
      "enable": options?.enable,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}








































/**
 * Generate RGB test pattern.

 *
 * @param options.size - set video size (default "320x240")
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @param options.complement - set complement colors (default false)
 * @see https://ffmpeg.org/ffmpeg-filters.html#allrgb_002c-allyuv_002c-color_002c-colorchart_002c-colorspectrum_002c-haldclutsrc_002c-nullsrc_002c-pal75bars_002c-pal100bars_002c-rgbtestsrc_002c-smptebars_002c-smptehdbars_002c-testsrc_002c-testsrc2_002c-yuvtestsrc
 */
export function rgbtestsrc(



  options?: {
    size?: FFImageSize;
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
    complement?: FFBoolean;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "rgbtestsrc", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
      "complement": options?.complement,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}












/**
 * Scale the input video size and/or convert the image format.

 *
 * @param options.w - Output video width
 * @param options.h - Output video height
 * @param options.flags - Flags to pass to libswscale (default "")
 * @param options.interl - set interlacing (default false)
 * @param options.size - set video size
 * @param options.in_color_matrix - set input YCbCr type (from -1 to 17) (default auto)
 * @param options.out_color_matrix - set output YCbCr type (from 0 to 17) (default 2)
 * @param options.in_range - set input color range (from 0 to 2) (default auto)
 * @param options.out_range - set output color range (from 0 to 2) (default auto)
 * @param options.in_chroma_loc - set input chroma sample location (from 0 to 6) (default auto)
 * @param options.out_chroma_loc - set output chroma sample location (from 0 to 6) (default auto)
 * @param options.in_primaries - set input primaries (from -1 to 22) (default auto)
 * @param options.out_primaries - set output primaries (from -1 to 22) (default auto)
 * @param options.in_transfer - set output color transfer (from -1 to 18) (default auto)
 * @param options.in_v_chr_pos - input vertical chroma position in luma grid/256 (from -513 to 512) (default -513)
 * @param options.in_h_chr_pos - input horizontal chroma position in luma grid/256 (from -513 to 512) (default -513)
 * @param options.out_v_chr_pos - output vertical chroma position in luma grid/256 (from -513 to 512) (default -513)
 * @param options.out_h_chr_pos - output horizontal chroma position in luma grid/256 (from -513 to 512) (default -513)
 * @param options.force_original_aspect_ratio - decrease or increase w/h if necessary to keep the original AR (from 0 to 2) (default disable)
 * @param options.force_divisible_by - enforce that the output resolution is divisible by a defined integer when force_original_aspect_ratio is used (from 1 to 256) (default 1)
 * @param options.reset_sar - reset SAR to 1 and scale to square pixels if scaling proportionally (default false)
 * @param options.param0 - Scaler param 0 (from -DBL_MAX to DBL_MAX) (default DBL_MAX)
 * @param options.param1 - Scaler param 1 (from -DBL_MAX to DBL_MAX) (default DBL_MAX)
 * @param options.eval - specify when to evaluate expressions (from 0 to 1) (default init)
 * @see https://ffmpeg.org/ffmpeg-filters.html#scale
 */
export function scale(



  options?: {
    w?: FFString;
    h?: FFString;
    flags?: FFString;
    interl?: FFBoolean;
    size?: FFString;
    in_color_matrix?: FFInt | "auto" | "bt601" | "bt470" | "smpte170m" | "bt470bg" | "bt709" | "fcc" | "smpte240m" | "bt2020" | "bt2020nc";
    out_color_matrix?: FFInt | "auto" | "bt601" | "bt470" | "smpte170m" | "bt470bg" | "bt709" | "fcc" | "smpte240m" | "bt2020" | "bt2020nc";
    in_range?: FFInt | "auto" | "unknown" | "full" | "limited" | "jpeg" | "mpeg" | "tv" | "pc";
    out_range?: FFInt | "auto" | "unknown" | "full" | "limited" | "jpeg" | "mpeg" | "tv" | "pc";
    in_chroma_loc?: FFInt | "auto" | "unknown" | "left" | "center" | "topleft" | "top" | "bottomleft" | "bottom";
    out_chroma_loc?: FFInt | "auto" | "unknown" | "left" | "center" | "topleft" | "top" | "bottomleft" | "bottom";
    in_primaries?: FFInt | "auto" | "bt709" | "bt470m" | "bt470bg" | "smpte170m" | "smpte240m" | "film" | "bt2020" | "smpte428" | "smpte431" | "smpte432" | "jedec-p22" | "ebu3213";
    out_primaries?: FFInt | "auto" | "bt709" | "bt470m" | "bt470bg" | "smpte170m" | "smpte240m" | "film" | "bt2020" | "smpte428" | "smpte431" | "smpte432" | "jedec-p22" | "ebu3213";
    in_transfer?: FFInt | "auto" | "bt709" | "bt470m" | "gamma22" | "bt470bg" | "gamma28" | "smpte170m" | "smpte240m" | "linear" | "iec61966-2-1" | "srgb" | "iec61966-2-4" | "xvycc" | "bt1361e" | "bt2020-10" | "bt2020-12" | "smpte2084" | "smpte428" | "arib-std-b67";
    in_v_chr_pos?: FFInt;
    in_h_chr_pos?: FFInt;
    out_v_chr_pos?: FFInt;
    out_h_chr_pos?: FFInt;
    force_original_aspect_ratio?: FFInt | "disable" | "decrease" | "increase";
    force_divisible_by?: FFInt;
    reset_sar?: FFBoolean;
    param0?: FFDouble;
    param1?: FFDouble;
    eval?: FFInt | "init" | "frame";
    eofAction?: FFString;
    shortest?: FFBoolean;
    repeatlast?: FFBoolean;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "scale", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "w": options?.w,
      "h": options?.h,
      "flags": options?.flags,
      "interl": options?.interl,
      "size": options?.size,
      "in_color_matrix": options?.in_color_matrix,
      "out_color_matrix": options?.out_color_matrix,
      "in_range": options?.in_range,
      "out_range": options?.out_range,
      "in_chroma_loc": options?.in_chroma_loc,
      "out_chroma_loc": options?.out_chroma_loc,
      "in_primaries": options?.in_primaries,
      "out_primaries": options?.out_primaries,
      "in_transfer": options?.in_transfer,
      "in_v_chr_pos": options?.in_v_chr_pos,
      "in_h_chr_pos": options?.in_h_chr_pos,
      "out_v_chr_pos": options?.out_v_chr_pos,
      "out_h_chr_pos": options?.out_h_chr_pos,
      "force_original_aspect_ratio": options?.force_original_aspect_ratio,
      "force_divisible_by": options?.force_divisible_by,
      "reset_sar": options?.reset_sar,
      "param0": options?.param0,
      "param1": options?.param1,
      "eval": options?.eval,
      "eof_action": options?.eofAction,
      "shortest": options?.shortest,
      "repeatlast": options?.repeatlast,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}










































































/**
 * Render a Sierpinski fractal.

 *
 * @param options.size - set frame size (default "640x480")
 * @param options.rate - set frame rate (default "25")
 * @param options.seed - set the seed (from -1 to UINT32_MAX) (default -1)
 * @param options.jump - set the jump (from 1 to 10000) (default 100)
 * @param options._type - set fractal type (from 0 to 1) (default carpet)
 * @see https://ffmpeg.org/ffmpeg-filters.html#sierpinski
 */
export function sierpinski(



  options?: {
    size?: FFImageSize;
    rate?: FFVideoRate;
    seed?: FFInt64;
    jump?: FFInt;
    _type?: FFInt | "carpet" | "triangle";
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "sierpinski", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "rate": options?.rate,
      "seed": options?.seed,
      "jump": options?.jump,
      "type": options?._type,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}








/**
 * Calculate the MPEG-7 video signature

 *
 * @param options.detectmode - set the detectmode (from 0 to 2) (default off)
 * @param options.nb_inputs - number of inputs (from 1 to INT_MAX) (default 1)
 * @param options.filename - filename for output files (default "")
 * @param options.format - set output format (from 0 to 1) (default binary)
 * @param options.th_d - threshold to detect one word as similar (from 1 to INT_MAX) (default 9000)
 * @param options.th_dc - threshold to detect all words as similar (from 1 to INT_MAX) (default 60000)
 * @param options.th_xh - threshold to detect frames as similar (from 1 to INT_MAX) (default 116)
 * @param options.th_di - minimum length of matching sequence in frames (from 0 to INT_MAX) (default 0)
 * @param options.th_it - threshold for relation of good to all frames (from 0 to 1) (default 0.5)
 * @see https://ffmpeg.org/ffmpeg-filters.html#signature
 */
export function signature(

  streams: FilterableStream[],

  options?: {
    detectmode?: FFInt | "off" | "full" | "fast";
    nb_inputs?: FFInt;
    filename?: FFString;
    format?: FFInt | "binary" | "xml";
    th_d?: FFInt;
    th_dc?: FFInt;
    th_xh?: FFInt;
    th_di?: FFInt;
    th_it?: FFDouble;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "signature", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "detectmode": options?.detectmode,
      "nb_inputs": options?.nb_inputs,
      "filename": options?.filename,
      "format": options?.format,
      "th_d": options?.th_d,
      "th_dc": options?.th_dc,
      "th_xh": options?.th_xh,
      "th_di": options?.th_di,
      "th_it": options?.th_it,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}










/**
 * Generate a sinc kaiser-windowed low-pass, high-pass, band-pass, or band-reject FIR coefficients.

 *
 * @param options.sample_rate - set sample rate (from 1 to INT_MAX) (default 44100)
 * @param options.nb_samples - set the number of samples per requested frame (from 1 to INT_MAX) (default 1024)
 * @param options.hp - set high-pass filter frequency (from 0 to INT_MAX) (default 0)
 * @param options.lp - set low-pass filter frequency (from 0 to INT_MAX) (default 0)
 * @param options.phase - set filter phase response (from 0 to 100) (default 50)
 * @param options.beta - set kaiser window beta (from -1 to 256) (default -1)
 * @param options.att - set stop-band attenuation (from 40 to 180) (default 120)
 * @param options.round - enable rounding (default false)
 * @param options.hptaps - set number of taps for high-pass filter (from 0 to 32768) (default 0)
 * @param options.lptaps - set number of taps for low-pass filter (from 0 to 32768) (default 0)
 * @see https://ffmpeg.org/ffmpeg-filters.html#sinc
 */
export function sinc(



  options?: {
    sample_rate?: FFInt;
    nb_samples?: FFInt;
    hp?: FFFloat;
    lp?: FFFloat;
    phase?: FFFloat;
    beta?: FFFloat;
    att?: FFFloat;
    round?: FFBoolean;
    hptaps?: FFInt;
    lptaps?: FFInt;
extraOptions?: Record<string, unknown>;
  },
): AudioStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "sinc", typingsInput: [], typingsOutput: ["audio"] },
    inputStreams,
    merge(
    {
      "sample_rate": options?.sample_rate,
      "nb_samples": options?.nb_samples,
      "hp": options?.hp,
      "lp": options?.lp,
      "phase": options?.phase,
      "beta": options?.beta,
      "att": options?.att,
      "round": options?.round,
      "hptaps": options?.hptaps,
      "lptaps": options?.lptaps,
},
    options?.extraOptions,
  ),
  );
return filterNode.audio(0) as unknown as AudioStream;
}






/**
 * Generate sine wave audio signal.

 *
 * @param options.frequency - set the sine frequency (from 0 to DBL_MAX) (default 440)
 * @param options.beep_factor - set the beep frequency factor (from 0 to DBL_MAX) (default 0)
 * @param options.sample_rate - set the sample rate (from 1 to INT_MAX) (default 44100)
 * @param options.duration - set the audio duration (default 0)
 * @param options.samples_per_frame - set the number of samples per frame (default "1024")
 * @see https://ffmpeg.org/ffmpeg-filters.html#sine
 */
export function sine(



  options?: {
    frequency?: FFDouble;
    beep_factor?: FFDouble;
    sample_rate?: FFInt;
    duration?: FFDuration;
    samples_per_frame?: FFString;
extraOptions?: Record<string, unknown>;
  },
): AudioStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "sine", typingsInput: [], typingsOutput: ["audio"] },
    inputStreams,
    merge(
    {
      "frequency": options?.frequency,
      "beep_factor": options?.beep_factor,
      "sample_rate": options?.sample_rate,
      "duration": options?.duration,
      "samples_per_frame": options?.samples_per_frame,
},
    options?.extraOptions,
  ),
  );
return filterNode.audio(0) as unknown as AudioStream;
}










/**
 * Generate SMPTE color bars.

 *
 * @param options.size - set video size (default "320x240")
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @see https://ffmpeg.org/ffmpeg-filters.html#allrgb_002c-allyuv_002c-color_002c-colorchart_002c-colorspectrum_002c-haldclutsrc_002c-nullsrc_002c-pal75bars_002c-pal100bars_002c-rgbtestsrc_002c-smptebars_002c-smptehdbars_002c-testsrc_002c-testsrc2_002c-yuvtestsrc
 */
export function smptebars(



  options?: {
    size?: FFImageSize;
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "smptebars", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}






/**
 * Generate SMPTE HD color bars.

 *
 * @param options.size - set video size (default "320x240")
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @see https://ffmpeg.org/ffmpeg-filters.html#allrgb_002c-allyuv_002c-color_002c-colorchart_002c-colorspectrum_002c-haldclutsrc_002c-nullsrc_002c-pal75bars_002c-pal100bars_002c-rgbtestsrc_002c-smptebars_002c-smptehdbars_002c-testsrc_002c-testsrc2_002c-yuvtestsrc
 */
export function smptehdbars(



  options?: {
    size?: FFImageSize;
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "smptehdbars", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}
























/**
 * Select video streams

 *
 * @param options.inputs - number of input streams (from 2 to INT_MAX) (default 2)
 * @param options.map - input indexes to remap to outputs
 * @see https://ffmpeg.org/ffmpeg-filters.html#streamselect_002c-astreamselect
 */
export function streamselect(

  streams: FilterableStream[],

  options?: {
    inputs?: FFInt;
    map?: FFString;
extraOptions?: Record<string, unknown>;
  },
): FilterNode {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "streamselect", typingsInput: [], typingsOutput: [] },
    inputStreams,
    merge(
    {
      "inputs": options?.inputs,
      "map": options?.map,
},
    options?.extraOptions,
  ),
  );
return filterNode;
}




















/**
 * Generate test pattern.

 *
 * @param options.size - set video size (default "320x240")
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @param options.decimals - set number of decimals to show (from 0 to 17) (default 0)
 * @see https://ffmpeg.org/ffmpeg-filters.html#allrgb_002c-allyuv_002c-color_002c-colorchart_002c-colorspectrum_002c-haldclutsrc_002c-nullsrc_002c-pal75bars_002c-pal100bars_002c-rgbtestsrc_002c-smptebars_002c-smptehdbars_002c-testsrc_002c-testsrc2_002c-yuvtestsrc
 */
export function testsrc(



  options?: {
    size?: FFImageSize;
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
    decimals?: FFInt;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "testsrc", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
      "decimals": options?.decimals,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}






/**
 * Generate another test pattern.

 *
 * @param options.size - set video size (default "320x240")
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @param options.alpha - set global alpha (opacity) (from 0 to 255) (default 255)
 * @see https://ffmpeg.org/ffmpeg-filters.html#allrgb_002c-allyuv_002c-color_002c-colorchart_002c-colorspectrum_002c-haldclutsrc_002c-nullsrc_002c-pal75bars_002c-pal100bars_002c-rgbtestsrc_002c-smptebars_002c-smptehdbars_002c-testsrc_002c-testsrc2_002c-yuvtestsrc
 */
export function testsrc2(



  options?: {
    size?: FFImageSize;
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
    alpha?: FFInt;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "testsrc2", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
      "alpha": options?.alpha,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}










































/**
 * UnPreMultiply first stream with first plane of second stream.

 *
 * @param options.planes - set planes (from 0 to 15) (default 15)
 * @param options.inplace - enable inplace mode (default false)
 * @see https://ffmpeg.org/ffmpeg-filters.html#unpremultiply
 */
export function unpremultiply(

  streams: FilterableStream[],

  options?: {
    planes?: FFInt;
    inplace?: FFBoolean;
    enable?: FFString;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "unpremultiply", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "planes": options?.planes,
      "inplace": options?.inplace,
      "enable": options?.enable,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}








































/**
 * Stack video inputs vertically.

 *
 * @param options.inputs - set number of inputs (from 2 to INT_MAX) (default 2)
 * @param options.shortest - force termination when the shortest input terminates (default false)
 * @see https://ffmpeg.org/ffmpeg-filters.html#vstack
 */
export function vstack(

  streams: FilterableStream[],

  options?: {
    inputs?: FFInt;
    shortest?: FFBoolean;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "vstack", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "inputs": options?.inputs,
      "shortest": options?.shortest,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}


















/**
 * Pick median pixels from several video inputs.

 *
 * @param options.inputs - set number of inputs (from 3 to 255) (default 3)
 * @param options.planes - set planes to filter (from 0 to 15) (default 15)
 * @param options.percentile - set percentile (from 0 to 1) (default 0.5)
 * @see https://ffmpeg.org/ffmpeg-filters.html#xmedian
 */
export function xmedian(

  streams: FilterableStream[],

  options?: {
    inputs?: FFInt;
    planes?: FFInt;
    percentile?: FFFloat;
    eofAction?: FFString;
    shortest?: FFBoolean;
    repeatlast?: FFBoolean;
    enable?: FFString;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "xmedian", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "inputs": options?.inputs,
      "planes": options?.planes,
      "percentile": options?.percentile,
      "eof_action": options?.eofAction,
      "shortest": options?.shortest,
      "repeatlast": options?.repeatlast,
      "enable": options?.enable,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}








/**
 * Stack video inputs into custom layout.

 *
 * @param options.inputs - set number of inputs (from 2 to INT_MAX) (default 2)
 * @param options.layout - set custom layout
 * @param options.grid - set fixed size grid layout
 * @param options.shortest - force termination when the shortest input terminates (default false)
 * @param options.fill - set the color for unused pixels (default "none")
 * @see https://ffmpeg.org/ffmpeg-filters.html#xstack
 */
export function xstack(

  streams: FilterableStream[],

  options?: {
    inputs?: FFInt;
    layout?: FFString;
    grid?: FFImageSize;
    shortest?: FFBoolean;
    fill?: FFString;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams = streams;

  const filterNode = filterNodeFactory(
    { name: "xstack", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "inputs": options?.inputs,
      "layout": options?.layout,
      "grid": options?.grid,
      "shortest": options?.shortest,
      "fill": options?.fill,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}










/**
 * Generate YUV test pattern.

 *
 * @param options.size - set video size (default "320x240")
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @see https://ffmpeg.org/ffmpeg-filters.html#allrgb_002c-allyuv_002c-color_002c-colorchart_002c-colorspectrum_002c-haldclutsrc_002c-nullsrc_002c-pal75bars_002c-pal100bars_002c-rgbtestsrc_002c-smptebars_002c-smptehdbars_002c-testsrc_002c-testsrc2_002c-yuvtestsrc
 */
export function yuvtestsrc(



  options?: {
    size?: FFImageSize;
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "yuvtestsrc", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}






/**
 * Generate zone-plate.

 *
 * @param options.size - set video size (default "320x240")
 * @param options.rate - set video rate (default "25")
 * @param options.duration - set video duration (default -0.000001)
 * @param options.sar - set video sample aspect ratio (from 0 to INT_MAX) (default 1/1)
 * @param options.precision - set LUT precision (from 4 to 16) (default 10)
 * @param options.xo - set X-axis offset (from INT_MIN to INT_MAX) (default 0)
 * @param options.yo - set Y-axis offset (from INT_MIN to INT_MAX) (default 0)
 * @param options.to - set T-axis offset (from INT_MIN to INT_MAX) (default 0)
 * @param options.k0 - set 0-order phase (from INT_MIN to INT_MAX) (default 0)
 * @param options.kx - set 1-order X-axis phase (from INT_MIN to INT_MAX) (default 0)
 * @param options.ky - set 1-order Y-axis phase (from INT_MIN to INT_MAX) (default 0)
 * @param options.kt - set 1-order T-axis phase (from INT_MIN to INT_MAX) (default 0)
 * @param options.kxt - set X-axis*T-axis product phase (from INT_MIN to INT_MAX) (default 0)
 * @param options.kyt - set Y-axis*T-axis product phase (from INT_MIN to INT_MAX) (default 0)
 * @param options.kxy - set X-axis*Y-axis product phase (from INT_MIN to INT_MAX) (default 0)
 * @param options.kx2 - set 2-order X-axis phase (from INT_MIN to INT_MAX) (default 0)
 * @param options.ky2 - set 2-order Y-axis phase (from INT_MIN to INT_MAX) (default 0)
 * @param options.kt2 - set 2-order T-axis phase (from INT_MIN to INT_MAX) (default 0)
 * @param options.ku - set 0-order U-color phase (from INT_MIN to INT_MAX) (default 0)
 * @param options.kv - set 0-order V-color phase (from INT_MIN to INT_MAX) (default 0)
 * @see https://ffmpeg.org/ffmpeg-filters.html#zoneplate
 */
export function zoneplate(



  options?: {
    size?: FFImageSize;
    rate?: FFVideoRate;
    duration?: FFDuration;
    sar?: FFRational;
    precision?: FFInt;
    xo?: FFInt;
    yo?: FFInt;
    to?: FFInt;
    k0?: FFInt;
    kx?: FFInt;
    ky?: FFInt;
    kt?: FFInt;
    kxt?: FFInt;
    kyt?: FFInt;
    kxy?: FFInt;
    kx2?: FFInt;
    ky2?: FFInt;
    kt2?: FFInt;
    ku?: FFInt;
    kv?: FFInt;
extraOptions?: Record<string, unknown>;
  },
): VideoStream {

  const inputStreams: FilterableStream[] = [];

  const filterNode = filterNodeFactory(
    { name: "zoneplate", typingsInput: [], typingsOutput: ["video"] },
    inputStreams,
    merge(
    {
      "size": options?.size,
      "rate": options?.rate,
      "duration": options?.duration,
      "sar": options?.sar,
      "precision": options?.precision,
      "xo": options?.xo,
      "yo": options?.yo,
      "to": options?.to,
      "k0": options?.k0,
      "kx": options?.kx,
      "ky": options?.ky,
      "kt": options?.kt,
      "kxt": options?.kxt,
      "kyt": options?.kyt,
      "kxy": options?.kxy,
      "kx2": options?.kx2,
      "ky2": options?.ky2,
      "kt2": options?.kt2,
      "ku": options?.ku,
      "kv": options?.kv,
},
    options?.extraOptions,
  ),
  );
return filterNode.video(0) as unknown as VideoStream;
}
