name: CI Scripts - Docs

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - 'src/scripts/**'
      - 'docs/**'
      - 'mkdocs.yml'
  pull_request:
    branches: [main]
    paths:
      - 'src/scripts/**'
      - 'docs/**'
      - 'mkdocs.yml'

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install --group dev

      - name: Build Mkdocs
        run: |
          source .venv/bin/activate
          mkdocs build
