name: CI Scripts - Test

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - 'src/scripts/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/scripts/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install GCC and ffmpeg
        run: sudo apt-get update && sudo apt-get install -y build-essential nasm ffmpeg && ffmpeg -version

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -r requirements.txt

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest src/scripts --cov=./src/scripts --cov-report=xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          file: ./coverage.xml
          flags: scripts,python-3.10
          name: scripts-coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
