name: CI Scripts - Lint

permissions:
  contents: read

on:
  push:
    branches: [main]
    paths:
      - 'src/scripts/**'
  pull_request:
    branches: [main]
    paths:
      - 'src/scripts/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install uv
        run: pip install uv

      - name: Create virtual environment
        run: uv venv

      - name: Install dependencies
        run: uv pip install --group dev

      - name: Run linting
        run: uv run pre-commit run --all-files
        working-directory: src/scripts
